#!/usr/bin/env python3
"""The device code of the Python Flash Next engine's CUDA extensions as zig/kernels/cuda/flashnext copies: each
source up to its first ATen-using function (comments kept, ATen/torch includes dropped), its anonymous namespace
kept (internal linkage, as Python compiles it), plus explicit instantiations of every template kernel the Python build instantiated (demangled from that
build's cubins with cu++filt). The same specializations, compiled from the same lines with the same flags.
usage: gen_copies.py <tensorfold src dir (the patched python engine)> <symbols.json of the Python cubins> <out dir>"""
import json, re, subprocess, sys
from pathlib import Path

SOURCES = {   # copy name: (source under src/tensorfold, the mangled file fragment of its kernels)
    "experts.cuh": ("cuda/experts.cuh", None),
    "experts.cu": ("cuda/experts.cu", "_10_experts_cu_"),
    "experts_prefill.cu": ("cuda/experts_prefill.cu", "_18_experts_prefill_cu_"),
    "gdn_prefill.cu": ("cuda/kernels/gdn_prefill.cu", "_14_gdn_prefill_cu_"),
    "qmm_frag.cuh": ("cuda/kernels/qmm_frag.cuh", None),
    "qmm.cu": ("cuda/kernels/qmm.cu", "_6_qmm_cu_"),
    "qmm_prefill.cu": ("cuda/kernels/qmm_prefill.cu", "_14_qmm_prefill_cu_"),
    "fn_gdn.cu": ("families/qwen4_exp/cuda/gdn.cu", None),          # fragment shared with cuda/kernels/gdn.cu: by cubin
    "gdn_io.cu": ("families/qwen4_exp/cuda/gdn_io.cu", "_9_gdn_io_cu_"),
}
HOST = re.compile(r"\bat::|\btorch::|\bTORCH_|\bC10_|PYBIND11")

def device_part(text: str) -> str:
    lines = text.splitlines()
    first = next((i for i, l in enumerate(lines) if HOST.search(l) and not l.startswith("#include")), len(lines))
    cut = first
    while cut > 0 and lines[cut - 1].strip():          # back to the start of that function's block
        cut -= 1
    keep = [l for l in lines[:cut] if not re.match(r"#include <(ATen|torch|c10)/", l)]
    body = "\n".join(keep).rstrip() + "\n"
    opened = body.count("namespace {")
    closed = len(re.findall(r"^}\s*//\s*(anonymous )?namespace", body, re.M))
    if opened > closed:
        body += "}  // namespace\n"
    return body

def split_args(text: str) -> list[str]:
    out, depth, cur = [], 0, ""
    for ch in text:
        if ch == "," and depth == 0:
            out.append(cur.strip()); cur = ""; continue
        depth += ch in "<(" ; depth -= ch in ">)"
        cur += ch
    return out + [cur.strip()]


def instantiations(symbols: list[str]) -> list[str]:
    out = subprocess.run(["cu++filt"], input="\n".join(symbols), capture_output=True, text=True, check=True).stdout
    lines = []
    for d in out.splitlines():
        d = d.replace("(anonymous namespace)::", "").replace("<unnamed>::", "")
        head = d.split("(", 1)[0]
        if "<" not in head:
            continue                                     # a plain __global__ function is emitted as written
        lt, depth = d.index("<"), 0
        for i in range(lt, len(d)):
            depth += d[i] == "<"; depth -= d[i] == ">"
            if depth == 0:
                break
        name = d[:i + 1]
        targs = split_args(name[name.index("<") + 1:name.rindex(">")])
        params = d[len(name):]
        params = re.sub(r"\bT(\d+)\b", lambda m: targs[int(m.group(1)) - 1], params)    # the demangler's Tn
        lines.append(f"template __global__ {name}{params};")
    seen, ordered = set(), []
    for l in lines:                                      # the cubin's own order (TF_ORDER=reverse flips it)
        if l not in seen:
            seen.add(l); ordered.append(l)
    import os
    return ordered[::-1] if os.environ.get("TF_ORDER") == "reverse" else ordered

def main() -> int:
    src, syms_path, out = Path(sys.argv[1]), json.loads(Path(sys.argv[2]).read_text()), Path(sys.argv[3])
    out.mkdir(parents=True, exist_ok=True)
    every = [s for v in syms_path.values() for s in v]
    for name, (rel, frag) in SOURCES.items():
        text = (src / rel).read_text()
        copy = device_part(text) if name.endswith(".cu") else text
        copy = copy.replace('#include "experts.cuh"', '#include "experts.cuh"')
        head = f"// Device code of src/tensorfold/{rel} (generated by zig/tests/cuda/flashnext/gen_copies.py; do not edit).\n"
        if name.endswith(".cu"):
            if frag is None:                             # qwen4_exp gdn.cu: its own cubin's symbols
                mine = [s for k, v in syms_path.items() if "qwen4_exp_gdn/" in k for s in v]
            else:
                mine = [s for s in every if frag in s]
            inst = instantiations(mine)
            # inside the anonymous namespace, as in the Python build: internal linkage, the same code generation
            copy += "\n// The specializations the Python build instantiated.\nnamespace {\n" + "\n".join(inst) + "\n}  // namespace\n"
            print(f"{name}: {len(inst)} template instantiations, {len(mine)} kernels")
        (out / name).write_text(head + copy)
    return 0

sys.exit(main())
